# Makefile for Hotplugs
# Don't allow optimizations unless specified.
cflags-y	+= -Os

obj-$(CONFIG_ASMP)           	        += autosmp.o
obj-$(CONFIG_BRICKED_HOTPLUG)           += bricked_hotplug.o
obj-$(CONFIG_DYNAMIC_HOTPLUG)           += dynamic_hotplug.o
obj-$(CONFIG_INTELLI_PLUG)              += intelli_plug.o
obj-$(CONFIG_MSM_HOTPLUG)		+= msm_hotplug.o
obj-$(CONFIG_THUNDER_PLUG)              += thunder_plug.o
obj-$(CONFIG_ZEN_DECISION)		+= msm_zen_decision.o
